#!/usr/bin/env python3
"""Reproduce the analytical and synthetic CMC tumour-transport study.

This program intentionally separates three evidence levels:
1. an analytical reaction--diffusion convergence test;
2. controlled heterogeneous tumour phantoms with known conductance;
3. an adapter/downloader for the open experimental spheroid dataset.

No clinical claim is generated by this script.
"""
from __future__ import annotations

import argparse
import json
import math
import os
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

import matplotlib.pyplot as plt
from matplotlib.patches import FancyBboxPatch, FancyArrowPatch
import numpy as np
import pandas as pd
import torch
import yaml

# Small dense/sparse operators are substantially faster without large BLAS thread pools.
torch.set_num_threads(1)
torch.set_num_interop_threads(1)

from cmc_tumour.complex import CubicalTumourComplex
from cmc_tumour.metrics import barrier_auc, penetration_fraction, relative_l2, rmse
from cmc_tumour.models import HodgeEdgeNet, PositiveEdgeMLP
from cmc_tumour.phantom import generate_sample
from cmc_tumour.transport import solve_transport_numpy, solve_transport_torch


def set_seed(seed: int) -> None:
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.use_deterministic_algorithms(True, warn_only=True)


def analytical_benchmark(out_data: Path, out_fig: Path) -> pd.DataFrame:
    """Incidence-matrix solution of -c'' + alpha^2 c = 0 on [0,1]."""
    alpha = 2.5
    rows = []
    profiles = []
    for n_intervals in (8, 16, 32, 64, 128):
        n = n_intervals + 1
        h = 1.0 / n_intervals
        D = np.zeros((n_intervals, n))
        for e in range(n_intervals):
            D[e, e] = -1.0
            D[e, e + 1] = 1.0
        A = (D.T @ D) / h**2 + alpha**2 * np.eye(n)
        b = np.zeros(n)
        # Strong Dirichlet rows; interior keeps the incidence-derived operator.
        A[0, :] = 0.0
        A[0, 0] = 1.0
        b[0] = 1.0
        A[-1, :] = 0.0
        A[-1, -1] = 1.0
        b[-1] = 0.0
        c = np.linalg.solve(A, b)
        x = np.linspace(0.0, 1.0, n)
        exact = np.sinh(alpha * (1.0 - x)) / np.sinh(alpha)
        err = np.sqrt(h * np.sum((c - exact) ** 2))
        max_err = np.max(np.abs(c - exact))
        rows.append({"n_intervals": n_intervals, "h": h, "l2_error": err, "max_error": max_err})
        if n_intervals in (8, 32, 128):
            profiles.append((x, c, exact, n_intervals))
    df = pd.DataFrame(rows)
    rates = [np.nan]
    for i in range(1, len(df)):
        rates.append(math.log(df.loc[i - 1, "l2_error"] / df.loc[i, "l2_error"]) /
                     math.log(df.loc[i - 1, "h"] / df.loc[i, "h"]))
    df["observed_order"] = rates
    df.to_csv(out_data / "analytical_convergence.csv", index=False)

    fig, ax = plt.subplots(figsize=(7.0, 4.8))
    ax.loglog(df["h"], df["l2_error"], "o-", label="CMC incidence solution")
    ref = df["l2_error"].iloc[-1] * (df["h"] / df["h"].iloc[-1]) ** 2
    ax.loglog(df["h"], ref, "--", label=r"second-order reference $O(h^2)$")
    ax.set_xlabel("cell spacing $h$")
    ax.set_ylabel(r"$L^2$ concentration error")
    ax.set_title("Analytical verification: one-dimensional reaction--diffusion")
    ax.grid(True, which="both", alpha=0.25)
    ax.legend()
    fig.tight_layout()
    fig.savefig(out_fig / "analytical_convergence.png", dpi=240)
    fig.savefig(out_fig / "analytical_convergence.pdf")
    plt.close(fig)

    fig, ax = plt.subplots(figsize=(7.0, 4.8))
    xfine = np.linspace(0, 1, 500)
    ax.plot(xfine, np.sinh(alpha * (1 - xfine)) / np.sinh(alpha), linewidth=2.4,
            label="analytical")
    for x, c, _, nint in profiles:
        ax.plot(x, c, marker="o", markersize=3, linewidth=1, label=f"CMC N={nint}")
    ax.set_xlabel("normalised depth")
    ax.set_ylabel("normalised therapeutic concentration")
    ax.set_title("Analytical and CMC concentration profiles")
    ax.grid(True, alpha=0.25)
    ax.legend(ncol=2)
    fig.tight_layout()
    fig.savefig(out_fig / "analytical_profiles.png", dpi=240)
    plt.close(fig)
    return df


def stack_samples(complex_: CubicalTumourComplex, seeds: list[int], reaction: float, penalty: float):
    samples = [generate_sample(complex_, s) for s in seeds]
    for sample in samples:
        sample["concentration"] = solve_transport_numpy(
            complex_, sample["conductance"], reaction_rate=reaction, penalty=penalty
        ).astype(np.float32)
    x = np.stack([s["edge_features"] for s in samples])
    g = np.stack([s["conductance"] for s in samples])
    c = np.stack([s["concentration"] for s in samples])
    return samples, x, g, c


def train_model(model, H_t, D_t, src_t, x_train, g_train, c_train,
                x_val, g_val, c_val, cfg, use_hodge: bool):
    """Train edge law with supervised conductance and periodic CMC physics loss.

    The periodic term differentiates through the conservative CMC solve on a
    fixed small subset. It is deliberately not evaluated on every step because
    dense batched linear solves dominate runtime on a CPU-only reproducibility
    environment.
    """
    device = torch.device("cpu")
    model.to(device)
    xtr = torch.tensor(x_train, dtype=torch.float32, device=device)
    gtr = torch.tensor(g_train, dtype=torch.float32, device=device)
    ctr = torch.tensor(c_train, dtype=torch.float32, device=device)
    xva = torch.tensor(x_val, dtype=torch.float32, device=device)
    gva = torch.tensor(g_val, dtype=torch.float32, device=device)
    cva = torch.tensor(c_val, dtype=torch.float32, device=device)
    opt = torch.optim.AdamW(model.parameters(), lr=float(cfg["learning_rate"]), weight_decay=1e-4)
    best = None
    best_val = float("inf")
    history = []
    physics_batch = min(int(cfg.get("physics_batch", 4)), xtr.shape[0])
    physics_ix = torch.arange(physics_batch, device=device)
    physics_every = int(cfg.get("physics_every", 5))

    def predict(xx):
        return model(xx, H_t) if use_hodge else model(xx)

    for epoch in range(int(cfg["epochs"])):
        model.train()
        opt.zero_grad(set_to_none=True)
        gp = predict(xtr)
        loss_g = torch.mean((torch.log(gp) - torch.log(gtr)) ** 2)
        loss_c = torch.zeros((), dtype=loss_g.dtype, device=device)
        if epoch % physics_every == 0 or epoch == int(cfg["epochs"]) - 1:
            cp = solve_transport_torch(D_t, gp[physics_ix], src_t,
                                       float(cfg["reaction_rate"]),
                                       float(cfg["dirichlet_penalty"]))
            loss_c = torch.mean((cp - ctr[physics_ix]) ** 2)
        loss = float(cfg["conductance_weight"]) * loss_g + float(cfg["physics_weight"]) * loss_c
        loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), 5.0)
        opt.step()

        model.eval()
        with torch.no_grad():
            gv = predict(xva)
            # Validation is primarily the constitutive error; concentration is
            # calculated at the periodic physics cadence.
            val_g = torch.mean((torch.log(gv) - torch.log(gva)) ** 2)
            val_c = torch.zeros((), dtype=val_g.dtype, device=device)
            if epoch % physics_every == 0 or epoch == int(cfg["epochs"]) - 1:
                cv = solve_transport_torch(D_t, gv[:min(3, len(gv))], src_t,
                                           float(cfg["reaction_rate"]),
                                           float(cfg["dirichlet_penalty"]))
                val_c = torch.mean((cv - cva[:min(3, len(gv))]) ** 2)
            val = val_g + float(cfg["physics_weight"]) * val_c
            val_f = float(val)
        history.append({"epoch": epoch + 1, "train_loss": float(loss.detach()),
                        "conductance_loss": float(loss_g.detach()),
                        "physics_loss": float(loss_c.detach()), "val_loss": val_f})
        if val_f < best_val:
            best_val = val_f
            best = {k: v.detach().cpu().clone() for k, v in model.state_dict().items()}
    if best is None:
        raise RuntimeError("training failed")
    model.load_state_dict(best)
    return model, pd.DataFrame(history)


def evaluate_models(complex_, samples, x, g_true, c_true, local_model, hodge_model,
                    H_t, cfg, homogeneous_g):
    xt = torch.tensor(x, dtype=torch.float32)
    local_model.eval(); hodge_model.eval()
    with torch.no_grad():
        g_local = local_model(xt).numpy()
        g_hodge = hodge_model(xt, H_t).numpy()
    models = {
        "Homogeneous continuum": np.full_like(g_true, homogeneous_g),
        "Local edge MLP": g_local,
        "CMC-HodgeNet": g_hodge,
        "Oracle CMC": g_true,
    }
    rows = []
    predictions = {}
    for name, gs in models.items():
        cps = np.stack([
            solve_transport_numpy(complex_, gs[i], float(cfg["reaction_rate"]),
                                  float(cfg["dirichlet_penalty"]))
            for i in range(len(samples))
        ])
        predictions[name] = (gs, cps)
        for i, sample in enumerate(samples):
            flux = gs[i] * (complex_.D @ cps[i])
            balance = complex_.D.T @ flux + float(cfg["reaction_rate"]) * cps[i]
            source_cells = complex_.source_mask
            interior_res = balance[~source_cells]
            rows.append({
                "model": name,
                "sample": i,
                "concentration_rmse": rmse(cps[i], c_true[i]),
                "concentration_relative_l2": relative_l2(cps[i], c_true[i]),
                "penetration_fraction_error": abs(penetration_fraction(cps[i]) - penetration_fraction(c_true[i])),
                "conductance_log_rmse": float(np.sqrt(np.mean((np.log(gs[i]) - np.log(g_true[i])) ** 2))),
                "barrier_auc": barrier_auc(gs[i], sample["barrier"]),
                "conservation_residual_linf": float(np.max(np.abs(interior_res))),
            })
    return pd.DataFrame(rows), predictions


def cell_grid(complex_: CubicalTumourComplex, values: np.ndarray) -> np.ndarray:
    arr = np.full(complex_.mask.shape, np.nan)
    arr[complex_.mask] = values
    return arr


def plot_phantom(complex_, sample, out_fig):
    fields = [
        (sample["stroma"], "stromal density"),
        (sample["necrosis"], "necrotic fraction"),
        (sample["endothelial"], "endothelial proximity"),
    ]
    fig, axes = plt.subplots(1, 3, figsize=(11.2, 3.7))
    for ax, (v, title) in zip(axes, fields, strict=True):
        im = ax.imshow(cell_grid(complex_, v), origin="lower")
        ax.set_title(title)
        ax.set_xticks([]); ax.set_yticks([])
        fig.colorbar(im, ax=ax, fraction=0.045, pad=0.03)
    fig.suptitle("Controlled heterogeneous breast-tumour spheroid phantom")
    fig.tight_layout()
    fig.savefig(out_fig / "phantom_fields.png", dpi=240)
    plt.close(fig)


def plot_complex(complex_, sample, out_fig):
    fig, ax = plt.subplots(figsize=(6.4, 5.6))
    xy = complex_.coords
    barrier = sample["barrier"] > 0.5
    for e, (u, v) in enumerate(complex_.edges):
        lw = 2.1 if barrier[e] else 0.45
        alpha = 0.9 if barrier[e] else 0.25
        ax.plot(xy[[u, v], 0], xy[[u, v], 1], linewidth=lw, alpha=alpha)
    ax.scatter(xy[:, 0], xy[:, 1], s=8, c=sample["stroma"], zorder=3)
    ax.scatter(xy[complex_.source_mask, 0], xy[complex_.source_mask, 1], s=34,
               marker="s", edgecolors="black", label="vascular/source cells", zorder=4)
    ax.set_aspect("equal"); ax.set_axis_off()
    ax.set_title("Physical cells and oriented CMC interfaces\n(thick interfaces are hidden transport barriers)")
    ax.legend(loc="lower left", frameon=True)
    fig.tight_layout()
    fig.savefig(out_fig / "intrinsic_complex.png", dpi=240)
    plt.close(fig)


def plot_transport(complex_, sample_i, predictions, c_true, out_fig):
    names = ["Homogeneous continuum", "Local edge MLP", "CMC-HodgeNet", "Oracle CMC"]
    fig, axes = plt.subplots(2, 4, figsize=(13.5, 6.5))
    true_grid = cell_grid(complex_, c_true[sample_i])
    for j, name in enumerate(names):
        c = predictions[name][1][sample_i]
        im = axes[0, j].imshow(cell_grid(complex_, c), origin="lower", vmin=0, vmax=1)
        axes[0, j].set_title(name)
        axes[0, j].set_xticks([]); axes[0, j].set_yticks([])
        err = np.abs(cell_grid(complex_, c) - true_grid)
        im2 = axes[1, j].imshow(err, origin="lower", vmin=0, vmax=np.nanmax(err) + 1e-12)
        axes[1, j].set_title(f"absolute error; rel. $L^2$={relative_l2(c, c_true[sample_i]):.3f}")
        axes[1, j].set_xticks([]); axes[1, j].set_yticks([])
        fig.colorbar(im2, ax=axes[1, j], fraction=0.042, pad=0.02)
    fig.colorbar(im, ax=axes[0, :].tolist(), fraction=0.015, pad=0.01,
                 label="normalised concentration")
    fig.suptitle("Therapeutic transport comparison on an unseen heterogeneous spheroid")
    fig.subplots_adjust(left=0.03, right=0.94, top=0.88, bottom=0.05, wspace=0.16, hspace=0.18)
    fig.savefig(out_fig / "transport_comparison.png", dpi=240)
    plt.close(fig)


def plot_metrics(summary, out_fig):
    order = ["Homogeneous continuum", "Local edge MLP", "CMC-HodgeNet", "Oracle CMC"]
    sub = summary.set_index("model").loc[order].reset_index()
    fig, ax = plt.subplots(figsize=(8.2, 4.8))
    ax.bar(np.arange(len(sub)), sub["concentration_relative_l2_mean"],
           yerr=sub["concentration_relative_l2_std"], capsize=4)
    ax.set_xticks(np.arange(len(sub)), ["Homogeneous", "Local MLP", "CMC-HodgeNet", "Oracle CMC"])
    ax.set_ylabel("test relative $L^2$ error")
    ax.set_title("Predictive accuracy on held-out tumour phantoms")
    ax.grid(axis="y", alpha=0.25)
    fig.tight_layout()
    fig.savefig(out_fig / "model_metrics.png", dpi=240)
    fig.savefig(out_fig / "model_metrics.pdf")
    plt.close(fig)


def plot_training(hist_local, hist_hodge, out_fig):
    fig, ax = plt.subplots(figsize=(7.2, 4.7))
    ax.plot(hist_local["epoch"], hist_local["val_loss"], label="Local edge MLP")
    ax.plot(hist_hodge["epoch"], hist_hodge["val_loss"], label="CMC-HodgeNet")
    ax.set_xlabel("epoch"); ax.set_ylabel("validation objective")
    ax.set_yscale("log"); ax.grid(True, alpha=0.25); ax.legend()
    ax.set_title("Physics-guided training history")
    fig.tight_layout(); fig.savefig(out_fig / "training_history.png", dpi=240); plt.close(fig)


def plot_workflow(out_fig):
    fig, ax = plt.subplots(figsize=(12.8, 6.6))
    ax.set_xlim(0, 12.8); ax.set_ylim(0, 6.6); ax.axis("off")
    boxes = [
        (0.4, 4.9, 2.7, 1.0, "Experimental 3D data\nLSFM images, masks, labels"),
        (3.5, 4.9, 2.7, 1.0, "Physical tumour mesh $\\mathcal{M}$\nsegmented cells and interfaces"),
        (6.6, 4.9, 2.7, 1.0, "Forman complex $\\mathcal{K}$\nquasi-cubical incidence structure"),
        (9.7, 4.9, 2.7, 1.0, "CMC transport\ncochains, Hodge map, balance"),
        (1.9, 2.6, 3.1, 1.0, "Topology-dependent operator learning\npositive CMC-HodgeNet conductance"),
        (5.25, 2.6, 2.3, 1.0, "Differentiable solve\n$D^T G_1 D c + R c = s$"),
        (7.85, 2.6, 3.1, 1.0, "Validation hierarchy\nanalytical, synthetic, experimental"),
        (4.7, 0.55, 3.5, 1.0, "Interpretable outputs\npenetration, barriers, uncertainty"),
    ]
    for x, y, w, h, text in boxes:
        patch = FancyBboxPatch((x, y), w, h, boxstyle="round,pad=0.08,rounding_size=0.12",
                               linewidth=1.3, facecolor="white", edgecolor="black")
        ax.add_patch(patch); ax.text(x+w/2, y+h/2, text, ha="center", va="center", fontsize=10)
    arrows = [((3.1,5.4),(3.5,5.4)),((6.2,5.4),(6.6,5.4)),((9.3,5.4),(9.7,5.4)),
              ((11.05,4.9),(9.3,3.6)),((6.4,4.9),(4.7,3.6)),((5.0,3.1),(5.25,3.1)),
              ((7.55,3.1),(7.85,3.1)),((9.4,2.6),(7.7,1.55)),((4.1,2.6),(5.1,1.55))]
    for a,b in arrows:
        ax.add_patch(FancyArrowPatch(a,b,arrowstyle="-|>",mutation_scale=13,linewidth=1.3,
                                     connectionstyle="arc3,rad=0.0"))
    ax.set_title("Intrinsic, topology-constrained learning workflow", fontsize=16, pad=12)
    fig.tight_layout(); fig.savefig(out_fig / "workflow.png", dpi=240); fig.savefig(out_fig / "workflow.pdf"); plt.close(fig)


def plot_experimental_design(out_fig):
    labels = ["T-47D breast carcinoma", "fibroblasts", "endothelial cells", "control / doxorubicin", "24 / 48 / 96 h"]
    fig, ax = plt.subplots(figsize=(9.4, 4.8))
    ax.axis("off"); ax.set_xlim(0, 10); ax.set_ylim(0, 5)
    ax.add_patch(plt.Circle((2.0,2.5), 1.35, fill=False, linewidth=2))
    rng=np.random.default_rng(9)
    for i in range(80):
        r=1.2*np.sqrt(rng.random()); t=2*np.pi*rng.random()
        ax.scatter(2+r*np.cos(t),2.5+r*np.sin(t),s=12,alpha=.65)
    ax.text(2,0.72,"multicellular spheroid",ha="center",fontsize=11)
    y=4.15
    for lab in labels:
        ax.add_patch(FancyBboxPatch((4.2,y-0.35),4.8,.58,boxstyle="round,pad=.05",facecolor="white",edgecolor="black"))
        ax.text(6.6,y-0.06,lab,ha="center",va="center",fontsize=10); y-=.78
    ax.add_patch(FancyArrowPatch((3.45,2.5),(4.1,2.5),arrowstyle="-|>",mutation_scale=15,linewidth=1.5))
    ax.set_title("Open experimental validation target (not bundled): Diosdi et al. 2025",fontsize=14)
    fig.tight_layout(); fig.savefig(out_fig / "experimental_design.png",dpi=240); plt.close(fig)


def export_complex_tables(complex_, sample, c, out_data):
    pd.DataFrame({
        "cell_id": np.arange(complex_.n_cells), "x": complex_.coords[:,0], "y": complex_.coords[:,1],
        "source": complex_.source_mask.astype(int), "degree": complex_.degree,
        "stroma": sample["stroma"], "necrosis": sample["necrosis"],
        "endothelial": sample["endothelial"], "concentration_true": c,
    }).to_csv(out_data / "cells.csv", index=False)
    u,v=complex_.edges[:,0],complex_.edges[:,1]
    pd.DataFrame({
        "edge_id":np.arange(complex_.n_edges),"tail_cell":u,"head_cell":v,
        "barrier":sample["barrier"],"conductance_true":sample["conductance"],
    }).to_csv(out_data / "interfaces.csv", index=False)
    np.savez_compressed(out_data / "incidence_and_hodge.npz", D=complex_.D.toarray(),
                        H=complex_.edge_hodge(), mask=complex_.mask, coords=complex_.coords,
                        edges=complex_.edges, source_mask=complex_.source_mask)


def main():
    parser=argparse.ArgumentParser()
    parser.add_argument("--config",default=str(ROOT/"configs/default.yaml"))
    args=parser.parse_args()
    cfg=yaml.safe_load(Path(args.config).read_text())
    out_data=ROOT/"data/demo"; out_fig=ROOT/"figures"; out_models=ROOT/"results/models"
    for p in (out_data,out_fig,out_models,ROOT/"results"): p.mkdir(parents=True,exist_ok=True)
    set_seed(int(cfg["seed"]))
    complex_=CubicalTumourComplex.circular(int(cfg["grid_size"]))
    total=int(cfg["n_train"])+int(cfg["n_val"])+int(cfg["n_test"])
    seeds=[int(cfg["seed"])+i*17 for i in range(total)]
    samples,x,g,c=stack_samples(complex_,seeds,float(cfg["reaction_rate"]),float(cfg["dirichlet_penalty"]))
    nt=int(cfg["n_train"]); nv=int(cfg["n_val"])
    train=slice(0,nt); val=slice(nt,nt+nv); test=slice(nt+nv,total)
    D_t=torch.tensor(complex_.D.toarray(),dtype=torch.float32)
    H=complex_.edge_hodge(); H_t=torch.tensor(H,dtype=torch.float32)
    src_t=torch.tensor(complex_.source_mask.astype(np.float32))
    in_dim=x.shape[-1]
    local=PositiveEdgeMLP(in_dim,int(cfg["hidden_dim"]))
    hodge=HodgeEdgeNet(in_dim,int(cfg["hidden_dim"]),int(cfg["hodge_layers"]))
    local,hist_l=train_model(local,H_t,D_t,src_t,x[train],g[train],c[train],x[val],g[val],c[val],cfg,False)
    hodge,hist_h=train_model(hodge,H_t,D_t,src_t,x[train],g[train],c[train],x[val],g[val],c[val],cfg,True)
    torch.save(local.state_dict(),out_models/"local_edge_mlp.pt")
    torch.save(hodge.state_dict(),out_models/"cmc_hodgenet.pt")
    homogeneous=float(np.exp(np.mean(np.log(g[train]))))
    metrics,pred=evaluate_models(complex_,samples[nt+nv:],x[test],g[test],c[test],local,hodge,H_t,cfg,homogeneous)
    metrics.to_csv(ROOT/"results/test_metrics_by_sample.csv",index=False)
    aggregations={col:["mean","std"] for col in ["concentration_rmse","concentration_relative_l2",
                    "penetration_fraction_error","conductance_log_rmse","barrier_auc","conservation_residual_linf"]}
    summary=metrics.groupby("model",sort=False).agg(aggregations)
    summary.columns=[f"{a}_{b}" for a,b in summary.columns]
    summary=summary.reset_index(); summary.to_csv(ROOT/"results/summary_metrics.csv",index=False)
    hist_l["model"]="Local edge MLP"; hist_h["model"]="CMC-HodgeNet"
    pd.concat([hist_l,hist_h]).to_csv(ROOT/"results/training_history.csv",index=False)
    analytical=analytical_benchmark(out_data,out_fig)
    plot_phantom(complex_,samples[nt+nv],out_fig); plot_complex(complex_,samples[nt+nv],out_fig)
    plot_transport(complex_,0,pred,c[test],out_fig); plot_metrics(summary,out_fig)
    plot_training(hist_l,hist_h,out_fig); plot_workflow(out_fig); plot_experimental_design(out_fig)
    export_complex_tables(complex_,samples[nt+nv],c[test][0],out_data)
    # Long-form predictions for exact reproducibility.
    records=[]
    for name,(gs,cs) in pred.items():
        for si in range(gs.shape[0]):
            for cid,val in enumerate(cs[si]): records.append({"model":name,"sample":si,"cell_id":cid,"concentration":val})
    pd.DataFrame(records).to_csv(ROOT/"results/test_concentrations.csv",index=False)
    run_meta={"configuration":cfg,"n_cells":complex_.n_cells,"n_interfaces":complex_.n_edges,
              "homogeneous_conductance":homogeneous,"software":{"numpy":np.__version__,"torch":torch.__version__}}
    (ROOT/"results/run_metadata.json").write_text(json.dumps(run_meta,indent=2))
    print(summary.to_string(index=False))
    print("\nAnalytical convergence:\n",analytical.to_string(index=False))

if __name__=="__main__":
    main()
